### ISSUE TITLE
Error getting requirements

### ISSUE THREAD

**Issue by huchukato** [cagliostrolab/forge-colab#12]
The build stops on this

```
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
Version: f2.0.1v1.10.1-previous-602-gd50f390c
Commit hash: d50f390c7e470761c5734221133bedc7f0febb65
Installing requirements
Traceback (most recent call last):
  File "/content/stable-diffusion-webui-forge/launch.py", line 54, in <module>
    main()
  File "/content/stable-diffusion-webui-forge/launch.py", line 42, in main
    prepare_environment()
  File "/content/stable-diffusion-webui-forge/modules/launch_utils.py", line 476, in prepare_environment
    run_pip(f"install -r \"{requirements_file}\"", "requirements")
  File "/content/stable-diffusion-webui-forge/modules/launch_utils.py", line 153, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "/content/stable-diffusion-webui-forge/modules/launch_utils.py", line 125, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install requirements.
Command: "/usr/bin/python3" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stderr: ERROR: Invalid requirement: '<<<<<<< Updated upstream': Expected package name at the start of dependency specifier
    <<<<<<< Updated upstream
    ^ (from line 31 of requirements_versions.txt)
```

**Comment by nawka12** [comment]
Hi, this is happening because we made changes to the requirements file.
For the time being, please uncheck both `update_extension` and `update_webui` until we made a fix.

**Comment by helloyanis** [comment]
After you get the error, you will always get it even when you start the notebook again after unchecking the two boxes.

What fixed it for me is the following...

- Uncheck both `update_extension` and `update_webui`
- Go to `Execution`, `Disconnect and delete execution environnement`
- Run the cell again!

**Comment by WallBreakerNO4** [comment]
is there an ETA of fixing this? i'm trying to use `NoobAI-XL-V-pred`, which only work on latest forge. With current version of webui forge, i'll only get broken images

**Comment by nawka12** [comment]
> is there an ETA of fixing this? i'm trying to use `NoobAI-XL-V-pred`, which only work on latest forge. With current version of webui forge, i'll only get broken images

Hi, first of all I'm sorry for the delay. Our team is extremely overwhelmed right now and will not be able to release a fix anytime soon. I can't promise an ETA either.

We're currently running into a deadline on one of our project. I hope you understand.

**Comment by crazylo** [comment]
I notice that the requirements dot txt has lot of errors, so I remake one for all to replace it.
[requirements_versions.txt](https://github.com/user-attachments/files/18290902/requirements_versions.txt)
