### ISSUE TITLE
the heck is this

### ISSUE THREAD

**Issue by Ayaya70** [cagliostrolab/forge-colab#14]
just tried to open casually the webui after starting the cell
is python crazy again

> Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
Version: f2.0.1v1.10.1-previous-634-g37301b22
Commit hash: 37301b2219cd7c38bc466b1d1acd6725bc8c9947
Fetching updates for google_blockly...
Checking out commit for google_blockly with hash: 1e98997c7fedaf5106af9849b6f50ebe5c4408f1...
Previous HEAD position was d9f9145 5
HEAD is now at 1e98997 8
Installing requirements
Traceback (most recent call last):
  File "/content/stable-diffusion-webui-forge/launch.py", line 54, in <module>
    main()
  File "/content/stable-diffusion-webui-forge/launch.py", line 42, in main
    prepare_environment()
  File "/content/stable-diffusion-webui-forge/modules/launch_utils.py", line 476, in prepare_environment
    run_pip(f"install -r \"{requirements_file}\"", "requirements")
  File "/content/stable-diffusion-webui-forge/modules/launch_utils.py", line 153, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "/content/stable-diffusion-webui-forge/modules/launch_utils.py", line 125, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install requirements.
Command: "/usr/bin/python3" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stderr: ERROR: Invalid requirement: '<<<<<<< Updated upstream': Expected package name at the start of dependency specifier
    <<<<<<< Updated upstream
    ^ (from line 31 of requirements_versions.txt)

**Comment by Ayaya70** [comment]
nvm seems double post, just saw #12 my bad
